### ISSUE TITLE
Got panic during streaming

### ISSUE THREAD

**Issue by mitchelp** [dweidenfeld/plexdrive#124]
Got myself a panic during streaming:
```
^[[0m^[[36m[USR/SBIN/PLEXDRIVE] [2017-05-22 16:15] INFO   : Starting playback of ko2q6vcksa2hfrogcf9pvgtk1gmj2escvkh292d43jacg8qndkckq126jqpgjr8lanj7r2la5eum312fq8kr2v85c9j48ultf2thqpsofagkiqr1kk3o4dk6u1lm5ih0
^[[0m^[[36m[USR/SBIN/PLEXDRIVE] [2017-05-22 16:15] INFO   : Stopping playback of ko2q6vcksa2hfrogcf9pvgtk1gmj2escvkh292d43jacg8qndkckq126jqpgjr8lanj7r2la5eum312fq8kr2v85c9j48ultf2thqpsofagkiqr1kk3o4dk6u1lm5ih0
^[[0m^[[36m[USR/SBIN/PLEXDRIVE] [2017-05-22 16:16] INFO   : Starting playback of ko2q6vcksa2hfrogcf9pvgtk1gmj2escvkh292d43jacg8qndkckq126jqpgjr8lanj7r2la5eum312fq8kr2v85c9j48ultf2thqpsofagkiqr1kk3o4dk6u1lm5ih0
^[[0mpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0298]

goroutine 2973316 [running]:
main.deleteOldestFile.func1(0xc4207b0900, 0x38, 0x0, 0x0, 0xd606a0, 0xc4209781b0, 0x0, 0x0)
        /home/dweidenfeld/Projects/golang/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc4201e8060, 0x1b, 0xd67260, 0xc420f6d520, 0xc4205d78e0, 0x0, 0x20)
        /usr/lib/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc4201e8060, 0x1b, 0xc4205d78e0, 0x8e8d40, 0x0)
        /usr/lib/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201e8060, 0x1b, 0x1abb0ba665, 0x0)
        /home/dweidenfeld/Projects/golang/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201e8060, 0x1b, 0x20, 0xc420649b30)
        /home/dweidenfeld/Projects/golang/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /home/dweidenfeld/Projects/golang/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /home/dweidenfeld/Projects/golang/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
```

**Comment by animosity22** [comment]
What settings are you launching it with?

**Comment by mitchelp** [comment]
```
${plexdrive} ${plexdrive_encrypt} \
              --clear-chunk-max-size=100G \
              -o allow_other \
              --refresh-interval=30s \
              --temp=/root/.plexdrive/tmp \
              -v 2 &>>/var/log/plexdrive_mount.log &
```
My chunks dir is filled up, I guess it's related. So I just emptied it, see how to go's because it just had again a panic. I think that it will be stable for a while again until the chunks dir is filled up again. We will see.

**Comment by mitchelp** [comment]
Could be or is related to the similar issue #104
