### ISSUE TITLE
Error after some hours over and over again.

### ISSUE THREAD

**Issue by bachph** [dweidenfeld/plexdrive#164]
Hi!

I'm using Plex Version 3.0.0 and get this error over and over again after some hours.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 1329 [running]:
main.deleteOldestFile.func1(0xc4211a9360, 0x49, 0x0, 0x0, 0xd646e0, 0xc420bb4570, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc420022700, 0x40, 0xd6b2a0, 0xc42117bc70, 0xc420203ec0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc4201e30b0, 0x23, 0xd6b2a0, 0xc420fdaf70, 0xc420203ec0, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc4201e30b0, 0x23, 0xc420203ec0, 0x8ed800, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201e30b0, 0x23, 0x4ff7b1c6e, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201e30b0, 0x23, 0xc420130180, 0x438c48)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
```

best regards,
Phil
```

**Comment by zenjabba** [comment]
fixed in 4.0.0 beta.. feel free to join us on the slack channel for access to the binaries and installation method.

**Comment by bachph** [comment]
After using 4.0.0 beta I got the following problem:

```
user@host ~ $ ~/run-plexdrive.sh
Mounting /home/user/gdrive/
[HOME/USER/PLEXDRIVE] [2017-06-08 16:38] ERROR  : Could not initialize cache
/home/user/run-plexdrive.sh: line 15: --temp=/home/user/.plexdrive/temp: No such file or directory
user@host ~ $ ls -al /home/user/.plexdrive/temp
total 0
drwxr-xr-x 2 user user  6 Jun  8 16:38 .
drwxr--r-- 4 user user 99 Jun  8 10:30 ..
```

my mount sctipt looks like this

```
PLEXDRIVECONFIGDIR="/home/user/.plexdrive"
LOGFILE="/home/user/.plexdrive/logs/plexdrive.log"
TMPDIR="/home/user/.plexdrive/temp"

PLEXDRIVEBIN="/home/user/plexdrive"
MPOINT="/home/user/gdrive/"

if mountpoint -q $MPOINT ; then
    echo "$MPOINT already mounted"
else
    echo "Mounting $MPOINT"
    $PLEXDRIVEBIN $MPOINT \
#                       --clear-chunk-max-size=60G \
                       --temp=$TMPDIR \
                       --config=$PLEXDRIVECONFIGDIR
                       --verbosity=3 \
                       &>>$LOGFILE
fi
```

Any ideas?

**Comment by zenjabba** [comment]
Fixed
