### ISSUE TITLE
Does Partial Scan work with PD

### ISSUE THREAD

**Issue by rrbailey89** [dweidenfeld/plexdrive#311]
I have partial scans enabled and it does not seem to be picking up anything, I have been having to manually update plex.

**Comment by felixbuenemann** [comment]
The FUSE filesystem does not have inode notification, so "Scan my library automatically" doesn't work.

The partial scan seems to be working, when you use the Plex API to add items.

**Comment by zmike808** [comment]
> I have partial scans enabled and it does not seem to be picking up anything, I have been having to manually update plex.

How are you adding the items? By uploading them to google drive and hoping plex will be able to notice them? Or are you adding it to the overlay between your local disk and plexdrive, and then copying/moving it to google drive afterwards?  The former won't allow plex to pick up media additions automatically. The latter will. And I highly recommend going with that option. You can just rclone move right after if you have minimal disk space. And for overlaying your local FS and plexdrive FS I highly recommend mergerfs

**Comment by mog54** [comment]
> > I have partial scans enabled and it does not seem to be picking up anything, I have been having to manually update plex.
> 
> How are you adding the items? By uploading them to google drive and hoping plex will be able to notice them? Or are you adding it to the overlay between your local disk and plexdrive, and then copying/moving it to google drive afterwards? The former won't allow plex to pick up media additions automatically. The latter will. And I highly recommend going with that option. You can just rclone move right after if you have minimal disk space. And for overlaying your local FS and plexdrive FS I highly recommend mergerfs

hello,

i understand the first option wont work. but i dont understand how to do the second.

right now i download files via a synology and then upload to google
synology and plex server are two different servers

**Comment by felixbuenemann** [comment]
I'm using [watcher](https://github.com/radovskyb/watcher) and a [custom python script](https://gist.github.com/f2314b3b67cbe7d5e22c3c616cfef449) and systemd service to do polling and partial library updates.

It's been running since March 2019 without problems.

**Comment by mog54** [comment]
Hello, 

thanks for info, i setup this, and ran manually for the moment, but when i add a media, it crash plex media scanner

`Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required`

**Comment by felixbuenemann** [comment]
It looks like your missing the '-pipe=true' command line option for watcher. Also make sure the LD_LIBRARY_PATH in plexwatcher.py is correct or the Plex Media Scanner will crash.

**Comment by mog54** [comment]
hello,

my ld_library_path point to /usr/lib/plexmediaserver/lib

it contain this 

root@plex:/usr/lib/plexmediaserver/lib# ls -l
total 57220
drwxr-xr-x 2 root root    4096 févr.  1 12:18 dri
-rw-r--r-- 1 root root 4361304 janv. 24 00:31 libavcodec.so.58
-rw-r--r-- 1 root root 5251352 janv. 24 00:31 libavfilter.so.7
-rw-r--r-- 1 root root 5094224 janv. 24 00:31 libavformat.so.58
-rw-r--r-- 1 root root  494632 janv. 24 00:31 libavutil.so.56
-rw-r--r-- 1 root root    8544 janv. 24 00:31 libboost_atomic.so
-rw-r--r-- 1 root root  167544 janv. 24 00:31 libboost_chrono.so
-rw-r--r-- 1 root root  169720 janv. 24 00:31 libboost_date_time.so
-rw-r--r-- 1 root root  242752 janv. 24 00:31 libboost_filesystem.so
-rw-r--r-- 1 root root  419544 janv. 24 00:31 libboost_iostreams.so
-rw-r--r-- 1 root root 1923352 janv. 24 00:31 libboost_locale.so
-rw-r--r-- 1 root root  773152 janv. 24 00:31 libboost_program_options.so
-rw-r--r-- 1 root root  161536 janv. 24 00:31 libboost_random.so
-rw-r--r-- 1 root root 1153552 janv. 24 00:31 libboost_regex.so
-rw-r--r-- 1 root root    8080 janv. 24 00:31 libboost_system.so
-rw-r--r-- 1 root root  337328 janv. 24 00:31 libboost_thread.so
-rw-r--r-- 1 root root  138040 janv. 24 00:31 libboost_timer.so
-rw-r--r-- 1 root root  540088 janv. 24 00:31 libcppnetlib-uri.so
-rw-r--r-- 1 root root 2574568 janv. 24 00:31 libcrypto.so.1.0.0
-rw-r--r-- 1 root root  458816 janv. 24 00:31 libcurl.so.4
-rw-r--r-- 1 root root  144984 janv. 24 00:31 libdrm_intel.so.1
-rw-r--r-- 1 root root   82936 janv. 24 00:31 libdrm.so.2
-rw-r--r-- 1 root root   89136 janv. 24 00:31 libexslt.so.0
-rw-r--r-- 1 root root  241456 janv. 24 00:31 libfmt.so.4
-rw-r--r-- 1 root root 7972656 janv. 24 00:31 libfreeimage.so
-rw-r--r-- 1 root root   97792 janv. 24 00:31 libhdhomerun.so
-rw-r--r-- 1 root root 1284112 janv. 24 00:31 libidn2.so
-rw-r--r-- 1 root root 1802792 janv. 24 00:31 libigdgmm.so.11
-rw-r--r-- 1 root root   30344 janv. 24 00:31 liblrc.so
-rw-r--r-- 1 root root   67984 janv. 24 00:31 libminiupnpc.so.10
-rw-r--r-- 1 root root  115800 janv. 24 00:31 libminizip.so
-rw-r--r-- 1 root root   13512 janv. 24 00:31 libnatpmp.so
-rw-r--r-- 1 root root 2865632 janv. 24 00:31 libopencv_core.so.3.1
-rw-r--r-- 1 root root 3139680 janv. 24 00:31 libopencv_imgproc.so.3.1
-rw-r--r-- 1 root root   48096 janv. 24 00:31 libpciaccess.so.0
-rw-r--r-- 1 root root 1881528 janv. 24 00:31 libpion.so
-rw-r--r-- 1 root root 5914448 janv. 24 00:31 libpython2.7.so.1.0
-rw-r--r-- 1 root root  472544 janv. 24 00:31 libsoci_core.so
-rw-r--r-- 1 root root  196368 janv. 24 00:31 libsoci_sqlite3.so
-rw-r--r-- 1 root root 1462872 janv. 24 00:31 libsqlite3.so
-rw-r--r-- 1 root root  509064 janv. 24 00:31 libssl.so.1.0.0
-rw-r--r-- 1 root root 1272424 janv. 24 00:31 libstdc++.so.6
-rw-r--r-- 1 root root  149912 janv. 24 00:31 libswresample.so.3
-rw-r--r-- 1 root root  829816 janv. 24 00:31 libswscale.so.5
-rw-r--r-- 1 root root 1392256 janv. 24 00:31 libtag.so.1
-rw-r--r-- 1 root root  102424 janv. 24 00:31 libusb-1.0.so.0
-rw-r--r-- 1 root root   15920 janv. 24 00:31 libva-drm.so.2
-rw-r--r-- 1 root root  151976 janv. 24 00:31 libva.so.2
-rw-r--r-- 1 root root 1588216 janv. 24 00:31 libxml2.so.2
-rw-r--r-- 1 root root  270128 janv. 24 00:31 libxslt.so.1
-rw-r--r-- 1 root root     885 janv. 24 01:16 plexmediaserver.default
-rwxr-xr-x 1 root root    1639 janv. 24 01:16 plexmediaserver.init
-rw-r--r-- 1 root root    1192 janv. 24 01:16 plexmediaserver.service


since i dont understand what im doing, i don't know if it's correct

thanks

**Comment by felixbuenemann** [comment]
Hmm, it's strange that those files are owned by root and not the plex user.

Can you run `ps aux | grep 'Plex Media Server'` and check what user the process `/usr/lib/plexmediaserver/Plex Media Server` is running at?

If the files in `/var/lib/plexmediaserver` are also owned by root you will probably run into permission problems, when you try to run the script as user plex.

**Comment by mog54** [comment]
hello,

its my plex user that run pms
`plex      4488  0.6  4.1 2683104 341524 ?      Ssl  17:40   1:16 /usr/lib/plexmediaserver/Plex Media Server`

there is the result of ` ls -l /var/lib/plexmediaserver/`
`total 8`
`drwxr-xr-x 4 plex plex 4096 févr.  5 17:39 Library`
`-rwxrwxrwx 1 plex plex 1942 févr.  3 18:48 plexwatcher.py`


for the moment, i just ran the cmd instead of script.
i dont get error when i ran cmd with plex user, but it do not show up in plex website

how can i launch plexwatcher.service with plex user?

thanks

**Comment by felixbuenemann** [comment]
The `plexwatcher.service` i posted already runs as user/group plex.

You can put the file in `/lib/systemd/system/plexwatcher.service` and then use `systemctl daemon-reload` and `systemctl start plexwatcher.service`.  You can then run `systemctl status plexwatcher.service` to see if it runs OK and if everything is fine you can enable it permanently with `systemctl enable plexwatcher.service`.

I think it is normal that you see no status spinner in the web frontend when manually calling the Plex Media Scanner, but the new media should pop up once it is done.

**Comment by felixbuenemann** [comment]
Oh and the `plexwatcher.service` in the gist assumes that your plexdrive is mounted by a systemd unit called `plexdrive.service`, so you need to change that if yours is called differently.

**Comment by mog54** [comment]
ok, my plexwatcher.service is in /lib/systemd/system/, i did daemon-reload

but my plexdrive.service is in /etc/systemd/system/, dont know if it can cause prob

thank for your time

**Comment by felixbuenemann** [comment]
That doesn't matter, both directories work fine.

**Comment by mog54** [comment]
i thinks its ok.

the script was running with error and i launch cmd at the same time, and i guess that why i got error.

i restart everything and its ok. no error in script status. i'm trying to add media and check how pms react. i'll let you know.

thanks again

**Comment by mog54** [comment]
hello, that's work from now.

the issue came from how i migrate my pms to a new server, i did a copy/paste of libray folder.

i try a fresh pms install with plexdrive and your script and thats work great.

thank you

**Comment by j0shii** [comment]
I have a problem with plexwatcher.py, with the movies everything is fine, but with the series I miss this error, what could it be?

FILE "The Good Doctor 4x10 Decrypt [AMZN WEB-DL 1080p H264 DD 2.0] [PXL] .mkv" CREATE [/ mnt / plexdrive / Plex / Series / The Good Doctor / The Good Doctor 4x10 Decrypt [AMZN WEB-DL 1080p H264 DD 2.0] [PXL] .mkv]
Traceback (most recent call last):
   File "/var/lib/plexmediaserver/plexwatcher.py", line 31, in <module>
     type = m.group ('type')
AttributeError: 'NoneType' object has no attribute 'group'
2021/03/03 02:01:53 exit status 1

**Comment by j0shii** [comment]
> I'm using [watcher](https://github.com/radovskyb/watcher) and a [custom python script](https://gist.github.com/f2314b3b67cbe7d5e22c3c616cfef449) and systemd service to do polling and partial library updates.
> 
> It's been running since March 2019 without problems.

I have a problem with plexwatcher.py, with the movies everything is fine, but with the series I miss this error, what could it be?

FILE "The Good Doctor 4x10 Decrypt [AMZN WEB-DL 1080p H264 DD 2.0] [PXL] .mkv" CREATE [/ mnt / plexdrive / Plex / Series / The Good Doctor / The Good Doctor 4x10 Decrypt [AMZN WEB-DL 1080p H264 DD 2.0] [PXL] .mkv]
Traceback (most recent call last):
   File "/var/lib/plexmediaserver/plexwatcher.py", line 31, in <module>
     type = m.group ('type')
AttributeError: 'NoneType' object has no attribute 'group'
2021/03/03 02:01:53 exit status 1

**Comment by WoisWoi** [comment]
> I'm using [watcher](https://github.com/radovskyb/watcher) and a [custom python script](https://gist.github.com/f2314b3b67cbe7d5e22c3c616cfef449) and systemd service to do polling and partial library updates.
> 
> It's been running since March 2019 without problems.

The Watcher installation process changed after the Go@v1.16, do you know if I have to change the watcher.go or anything ? I don't know if it's properly installed.

**Comment by TheCreatorzOne** [comment]
@WoisWoi I found out my watcher binary was installed to the folder where I ran go from (i.e. for me it was "/home/username/go/bin/watcher"). Then I changed the service file exec line from "ExecStart=/usr/local/bin/watcher ..........." to "ExecStart=/home/username/go/bin/watcher ............"

Check where your watcher binary file has been downloaded 👍
