### ISSUE TITLE
Generic Crash (debug logs posted)

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#79]
```
[SBIN/PLEXDRIVE] [2017-05-16 00:40] INFO   : Starting playback of poster.jpg
[SBIN/PLEXDRIVE] [2017-05-16 00:40] DEBUG  : Creating buffer for object 0BxYemFFjZ8ptclczMkdRS2tkbnM
[SBIN/PLEXDRIVE] [2017-05-16 00:40] DEBUG  : Getting object 0BxYemFFjZ8ptclczMkdRS2tkbnM - chunk 0 - offset 0 for 4096 bytes (is preload: false)
[SBIN/PLEXDRIVE] [2017-05-16 00:40] DEBUG  : Requesting object 0BxYemFFjZ8ptclczMkdRS2tkbnM bytes 0 - 5242880 from API
[SBIN/PLEXDRIVE] [2017-05-16 00:40] DEBUG  : Cleaning empty directory /dev/shm/chunks/0BxYemFFjZ8ptcHlhbkNxdHEyVVE
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7e1e9f]

goroutine 7534293 [running]:
main.dirSize.func1(0xc4225b9440, 0x2c, 0x0, 0x0, 0xda2700, 0xc4225b9500, 0x0, 0x0)
        /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:292 +0x2f
path/filepath.walk(0xc4201dc560, 0xf, 0xda9280, 0xc4208a4410, 0xc420660750, 0x0, 0x10)
        /usr/lib/go-1.8/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc4201dc560, 0xf, 0xc420660750, 0x4, 0xc420160070)
        /usr/lib/go-1.8/src/path/filepath/path.go:398 +0x14c
main.dirSize(0xc4201dc560, 0xf, 0xc421233e30, 0x7d3178, 0xc423605fa8)
        /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:296 +0x9c
main.cleanChunkDir(0xc4201dc560, 0xf, 0xc4200fa240, 0xda6a00)
        /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:253 +0x39
main.(*Buffer).ReadBytes.func1()
        /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:157 +0x3d
created by main.(*Buffer).ReadBytes
        /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:161 +0x172f
```

**Comment by dweidenfeld** [comment]
I think the problem is, that some files are deleted externally by your system in /dev/shm/chunks/* while plexdrive is running and trying to access those files.
This is generally not a problem with plexdrive, but with the /dev/shm/ setup. 

I implemented a better error check so that the program should not crash even if the file does not exist anymore.
The problem here is, that plexdrive does not assume that the system is deleting files while plexdrive is running, so there could be more problems with plexdrive if the system deletes those files. Please just open issues if you see other issues like that in the future.
