### ISSUE TITLE
Plexdrive crashes suddenly

### ISSUE THREAD

**Issue by arvdsn** [dweidenfeld/plexdrive#80]
Not sure why this happens, but this is what syslog says. I just restarted it to get it working again. Thought I'd report it :)

Edit: It happened again now.

```
>May 16 11:19:21 plex plexdrive[18608]: panic: runtime error: invalid memory address or nil pointer dereference
May 16 11:19:21 plex plexdrive[18608]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7df4cf]
May 16 11:19:21 plex plexdrive[18608]: goroutine 1247476 [running]:
May 16 11:19:21 plex plexdrive[18608]: main.dirSize.func1(0xc420f37600, 0x33, 0x0, 0x0, 0xd9c6e0, 0xc420866ed0, 0x0, 0x0)
May 16 11:19:21 plex plexdrive[18608]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:270 +0x2f
May 16 11:19:21 plex plexdrive[18608]: path/filepath.walk(0xc420866e10, 0x28, 0xda3260, 0xc420cf1d40, 0xc4206565c0, 0x0, 0x0)
May 16 11:19:21 plex plexdrive[18608]: #011/usr/local/go/src/path/filepath/path.go:372 +0x2fe
May 16 11:19:21 plex plexdrive[18608]: path/filepath.walk(0xc4201d2410, 0xb, 0xda3260, 0xc4209420d0, 0xc4206565c0, 0x0, 0x10)
May 16 11:19:21 plex plexdrive[18608]: #011/usr/local/go/src/path/filepath/path.go:376 +0x414
May 16 11:19:21 plex plexdrive[18608]: path/filepath.Walk(0xc4201d2410, 0xb, 0xc4206565c0, 0x4, 0xc420156a10)
May 16 11:19:21 plex plexdrive[18608]: #011/usr/local/go/src/path/filepath/path.go:398 +0x14c
May 16 11:19:21 plex plexdrive[18608]: main.dirSize(0xc4201d2410, 0xb, 0x393533353837332f, 0x7d1098, 0xc422b92fa8)
May 16 11:19:21 plex plexdrive[18608]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:274 +0x9c
May 16 11:19:21 plex plexdrive[18608]: main.cleanChunkDir(0xc4201d2410, 0xb, 0xc4200d60c0, 0xda09e0)
May 16 11:19:21 plex plexdrive[18608]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:231 +0x39
May 16 11:19:21 plex plexdrive[18608]: main.(*Buffer).ReadBytes.func1()
May 16 11:19:21 plex plexdrive[18608]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:149 +0x3d
May 16 11:19:21 plex plexdrive[18608]: created by main.(*Buffer).ReadBytes
May 16 11:19:21 plex plexdrive[18608]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:153 +0xff2
May 16 11:19:21 plex systemd[1]: plexdrive.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 11:19:22 plex systemd[1]: plexdrive.service: Unit entered failed state.
May 16 11:19:22 plex systemd[1]: plexdrive.service: Failed with result 'exit-code'.
```

**Comment by dweidenfeld** [comment]
#79
