### ISSUE TITLE
segfault: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by peatnik** [dweidenfeld/plexdrive#83]
Hey,

i am doing a full plex scan of a big library and after a while (maybe an hour?) plexdrive will always segfault.

version: `plexdrive --version: 2.1.1`
cli parameters: `plexdrive /media/sorted/scannable -v 3 -o allow_other,read_only --gid=1000 --uid=1000 --chunk-size=10M --clear-chunk-age=30m --clear-chunk-max-size=80G --clear-chunk-interval=1m --refresh-interval=5m --temp="/media/sorted/.pdtemp"`

Here is the trace:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7df3a8]

goroutine 1209832 [running]:
main.deleteOldestFile.func1(0xc421392800, 0x3b, 0x0, 0x0, 0xd9c6e0, 0xc4230705d0, 0x0, 0x0)
    /go/src/github.com/dweidenfeld/plexdrive/buffer.go:251 +0x38
path/filepath.walk(0xc4201dadc0, 0x1e, 0xda3260, 0xc425aa9a00, 0xc420639500, 0x0, 0x20)
    /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc4201dadc0, 0x1e, 0xc420639500, 0xc4201dadc0, 0x1e)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201dadc0, 0x1e, 0x17c017ed0e, 0x0)
    /go/src/github.com/dweidenfeld/plexdrive/buffer.go:259 +0x10c
main.cleanChunkDir(0xc4201dadc0, 0x1e, 0xc420504000, 0xda09e0)
    /go/src/github.com/dweidenfeld/plexdrive/buffer.go:237 +0x98
main.(*Buffer).ReadBytes.func1()
    /go/src/github.com/dweidenfeld/plexdrive/buffer.go:149 +0x3d
    created by main.(*Buffer).ReadBytes
    /go/src/github.com/dweidenfeld/plexdrive/buffer.go:153 +0xff2
```

Two somewhat related side notes:
1. The --temp dir uses 95GB instead of the specified 80G.
2. Do you think a logfile flag might be useful for plexdrive so that logs would be automatically written?

Thanks for taking the time!

**Comment by zenjabba** [comment]
fixed in 3.0. I had the same problem

**Comment by kageurufu** [comment]
I just ran into this on 3.0

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 9012693 [running]:
main.deleteOldestFile.func1(0xc42099f4a0, 0x28, 0x0, 0x0, 0xd646e0, 0xc42099f500, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc420191910, 0xb, 0xd6b2a0, 0xc421cae680, 0xc4220720a0, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc420191910, 0xb, 0xc4220720a0, 0x8ed800, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc420191910, 0xb, 0x5ea95db17, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc420191910, 0xb, 0xc4200143e0, 0x438c48)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
```

cache is on an ssd

**Comment by peatnik** [comment]
@kageurufu see https://github.com/dweidenfeld/plexdrive/issues/104
